DROP TABLE ORDER_PRODUCT_TEMP
/
DROP TABLE ORDER_TEMP
/
DROP TABLE PRODUCT_TEMP
/
DROP TABLE CATEGORY_TEMP
/
DROP TABLE CUSTOMER_TEMP
/
DROP TABLE GEOGRAPHY_TEMP
/
CREATE TABLE GEOGRAPHY_TEMP (
    GEOGRAPHY_ID NUMBER(5) UNIQUE,
    COUNTRY_NAME VARCHAR2(127 BYTE),
    STATE_NAME VARCHAR2(127 BYTE),
    CITY_NAME VARCHAR2(127 BYTE),
    CONSTRAINT PK_GT PRIMARY KEY(COUNTRY_NAME, STATE_NAME, CITY_NAME)
)
/
CREATE TABLE CUSTOMER_TEMP (
    CUSTOMER_ID NUMBER(5) PRIMARY KEY,
    EMAILID VARCHAR2(128 BYTE)
)
/
CREATE TABLE CATEGORY_TEMP (
    CATEGORY_ID NUMBER(5) PRIMARY KEY,
    CATEGORY VARCHAR2(26 BYTE)
)
/
CREATE TABLE PRODUCT_TEMP (
    PRODUCT_ID NUMBER(5) PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(128 BYTE),
    CATEGORY_ID NUMBER(5) REFERENCES CATEGORY_TEMP(CATEGORY_ID)
)
/
CREATE TABLE ORDER_TEMP (
    ORDER_ID NUMBER(5) PRIMARY KEY,
    STRING_ORDER_ID VARCHAR2(26 BYTE),
    ORDER_DATE DATE,
    SHIP_DATE DATE,
    CUSTOMER_ID NUMBER(5) REFERENCES CUSTOMER_TEMP(CUSTOMER_ID),
    GEOGRAPHY_ID NUMBER(5) REFERENCES GEOGRAPHY_TEMP(GEOGRAPHY_ID)
)
/
CREATE TABLE ORDER_PRODUCT_TEMP (
    ORDER_PRODUCT_ID NUMBER(5) PRIMARY KEY,
    ORDER_ID NUMBER(5) REFERENCES ORDER_TEMP(ORDER_ID),
    PRODUCT_ID NUMBER(5) REFERENCES PRODUCT_TEMP(PRODUCT_ID),
    SALES NUMBER(38,3),
    QUANTITY NUMBER(38,0),
    PROFIT NUMBER(38,4)
);
