DROP SEQUENCE TEMP_CATEGORY_SEQ
/
DROP SEQUENCE TEMP_CUSTOMER_SEQ
/
DROP SEQUENCE TEMP_GEOGRAPHY_SEQ
/
DROP SEQUENCE TEMP_ORDER_PRODUCT_SEQ
/
DROP SEQUENCE TEMP_ORDER_SEQ
/
DROP SEQUENCE TEMP_PRODUCT_SEQ
/
CREATE SEQUENCE TEMP_CATEGORY_SEQ 
START WITH 1
INCREMENT BY 1
/
CREATE SEQUENCE TEMP_CUSTOMER_SEQ
START WITH 1
INCREMENT BY 1
/
CREATE SEQUENCE TEMP_GEOGRAPHY_SEQ
START WITH 1
INCREMENT BY 1
/
CREATE SEQUENCE TEMP_ORDER_PRODUCT_SEQ
START WITH 1
INCREMENT BY 1
/
CREATE SEQUENCE TEMP_ORDER_SEQ
START WITH 1
INCREMENT BY 1
/
CREATE SEQUENCE TEMP_PRODUCT_SEQ
START WITH 1
INCREMENT BY 1
/
CREATE OR REPLACE TRIGGER TEMP_CATEGORY_TRIGGER
BEFORE INSERT ON CATEGORY_TEMP
FOR EACH ROW
BEGIN
    SELECT TEMP_CATEGORY_SEQ.NEXTVAL INTO :NEW.CATEGORY_ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER TEMP_CUSTOMER_TRIGGER
BEFORE INSERT ON CUSTOMER_TEMP
FOR EACH ROW
BEGIN
    SELECT TEMP_CUSTOMER_SEQ.NEXTVAL INTO :NEW.CUSTOMER_ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER TEMP_GEOGRAPHY_TRIGGER
BEFORE INSERT ON GEOGRAPHY_TEMP
FOR EACH ROW
BEGIN
    SELECT TEMP_GEOGRAPHY_SEQ.NEXTVAL INTO :NEW.GEOGRAPHY_ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER TEMP_ORDER_PRODUCT_TRIGGER
BEFORE INSERT ON ORDER_PRODUCT_TEMP
FOR EACH ROW
BEGIN
    SELECT TEMP_ORDER_PRODUCT_SEQ.NEXTVAL INTO :NEW.ORDER_PRODUCT_ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER TEMP_ORDER_TRIGGER
BEFORE INSERT ON ORDER_TEMP
FOR EACH ROW
BEGIN
    SELECT TEMP_ORDER_SEQ.NEXTVAL INTO :NEW.ORDER_ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER PRODUCT_SEQ
BEFORE INSERT ON PRODUCT_TEMP
FOR EACH ROW
BEGIN
    SELECT TEMP_PRODUCT_SEQ.NEXTVAL INTO :NEW.PRODUCT_ID FROM DUAL;
END;
